### ISSUE TITLE
Is rspirv too abstracted?

### ISSUE THREAD

**Issue by Skepfyr** [gfx-rs/rspirv#107]
`rspirv` is a binary to AST parser, but I'm not sure it looks like one any more. To me, it looks a lot larger and more complex than I would expect, just from an overhead PoV and also knowing how much it actually does atm.

The current complexity of the application makes a lot of things that it should be doing awkward and convoluted. The current error handling story is a bit of a mess (getting a list of issues that occurred would be hard to get working), mostly just because of how layered everything is.

The autogen is also a problem. The level of metaprogramming trying to get it to output something you want seems silly. To me for the changes we've made in the past few months have been more suited to sed than to rust, and we aren't exactly expecting the SPIR-V spec to be changing wildly over the years to come.

After looking through each high-level part of the application (sr, dr, binary) I'm generally happy with how each bit is structured. It's just when viewing the application as a whole that something seems off, which is what has led me to believe that the project is just currently too abstracted.

I've been looking at all these as separate issues for a while but, after stepping back, I think we might need for of a shift in mindset (and maybe get a bit more free with the delete key!) to really tackle these issues. I hope no-one takes me the wrong way with this, I really like `rspirv`s goal and I truly do think that each individual bit is well designed for its own goal, it's just the project as a whole that has been eating away at me recently.

**Comment by kvark** [comment]
I appreciate the feedback, thank you! Could you try to transform it into a more actionable state, i.e. perhaps file separate issues for the parser error handling, autogen, and whatever else, so that we can find out a solution (instead of mixing it all up here).

**Comment by Skepfyr** [comment]
I'm happy that there are now (or will be) processes to consider this and time to discuss it, so I'm raising the error handling issue explicitly and closing this.
