### ISSUE TITLE
Cargo.lock in tree

### ISSUE THREAD

**Issue by Skepfyr** [gfx-rs/rspirv#113]
I flip-flop randomly between believing that Cargo.lock should be included in a library repo, but I thought I'd raise this for discussion seen as it was mentioned in #100. The rust documentation does advise against it [(FAQ)](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries), but I occasionally see a good argument for it. In general, I think it's probably a good idea to remove it.

**Comment by kvark** [comment]
I think we should remove it, since this is a Rust library, and the end users will have their own lockfiles.

**Comment by antiagainst** [comment]
We actually have a binary [`rspirv-dis`](https://github.com/gfx-rs/rspirv/blob/master/dis/main.rs) in tree. So this repo contains both libraries and binaries using workspaces. I'm not sure how does it plays out? Is it possible to make the lock file dis only?

**Comment by kvark** [comment]
Let's just keep the lock then.
