### ISSUE TITLE
sr::gen_sr_code_from_instruction_grammar generates wrong type

### ISSUE THREAD

**Issue by Lichtso** [gfx-rs/rspirv#131]
The `ty` field of `rspirv::sr::Type::Pointer` is wrong: It should be `Token<Type>` but is generated as `spirv::Word` instead.

**Comment by Jasper-Bekkers** [comment]
@Lichtso Could you review #152 and see if it fixes your use-case?

**Comment by Lichtso** [comment]
Looks good to me, thanks!

**Comment by Jasper-Bekkers** [comment]
Perfect.
