### ISSUE TITLE
Transfer ownership & maintenance to EmbarkStudios

### ISSUE THREAD

**Issue by arirawr** [gfx-rs/rspirv#160]
A few engineers from Embark (primarily @Jasper-Bekkers and @khyperia) have been submitting changes to this repo for a while, and we're actively depending on it for our work. As gfx-rs no longer depends on it, we thought it would make sense to transfer the repo over to the EmbarkStudios organisation.

Changes would be as follows:
- [ ] Transfer the repo itself to [EmbarkStudios](https://github.com/EmbarkStudios)
- [ ] Adopt [Embark's Code of Conduct](https://github.com/EmbarkStudios/opensource-template/blob/main/CODE_OF_CONDUCT.md). Approval needed from @antiagainst.
- [ ] Re-license the project to dual Apache 2.0 OR MIT. Approval needed from all prior contributors, to be done via GitHub issue.

@antiagainst could you please let us know if you would be alright with these changes? We have already discussed and gotten the go-ahead from @kvark  :)

**Comment by antiagainst** [comment]
Hi, it's great to see that rspirv being useful to you folks and thanks for the contribution and maintanance! If gfx-rs is not interested in hosting this repo anymore, I'm wondering whether moving it back to my personal account is a workable solution for you folks. I'm happy to give all necessary admin rights so you can shape the project to faciliate your use cases. I don't have the bandwidth to actively working on this at the moment, but I still hope to come back to this some time later. Let me know how you think. :)

**Comment by arirawr** [comment]
Hey @antiagainst - thanks for the response.
It doesn't make too much difference to us whether it's on the gfx org or your personal account, so I'll let you and @kvark decide that 😄 
I'll go ahead and close this issue.
Thanks again for your work on the project 🎉

**Comment by kvark** [comment]
@antiagainst if we transfer it back to you, would you still review `spirv_headers` changes at least?
