### ISSUE TITLE
Update derive_more dependency

### ISSUE THREAD

**Issue by XAMPPRocky** [gfx-rs/rspirv#172]
Currently the `derive_more` dependency is pretty old (`0.15` when the current version is `0.99`), and is currently causing a lot of duplicate subdependencies in `rust-gpu`, which is using newer versions of the same dependencies `derive_more` depends on. I tried to update it myself to make a PR, but there has been some breaking changes in what `derive_more` generates, and it breaks some of the auto generated code.

```
error[E0119]: conflicting implementations of trait `std::convert::From<u32>` for type `dr::constructs::Operand`:
 --> rspirv/dr/autogen_operand.rs:6:35
  |
6 | #[derive(Clone, Debug, PartialEq, From)]
  |                                   ^^^^
  |                                   |
  |                                   first implementation here
  |                                   conflicting implementation for `dr::constructs::Operand`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `std::convert::From<u32>` for type `sr::autogen_decoration::Decoration`:
 --> rspirv/sr/autogen_decoration.rs:8:56
  |
8 | #[derive(Clone, Debug, Eq, PartialEq, PartialOrd, Ord, From)]
  |                                                        ^^^^
  |                                                        |
  |                                                        first implementation here
  |                                                        conflicting implementation for `sr::autogen_decoration::Decoration`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `std::convert::From<std::string::String>` for type `sr::autogen_decoration::Decoration`:
 --> rspirv/sr/autogen_decoration.rs:8:56
  |
8 | #[derive(Clone, Debug, Eq, PartialEq, PartialOrd, Ord, From)]
  |                                                        ^^^^
  |                                                        |
  |                                                        first implementation here
  |                                                        conflicting implementation for `sr::autogen_decoration::Decoration`
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by MarijnS95** [comment]
Hi @XAMPPRocky, I've previously [explored](https://github.com/gfx-rs/rspirv/pull/142#issuecomment-668042364) this path and the problem is that newer `derive_more` does not omit duplicate `impl From<>`, instead requiring us to manually add `#[from(ignore)]`.

Either:
- We take this issue to `derive_more` and ask to reintroduce this behaviour;
- Add some extra logic in the autogenerator to emit `#[from(ignore)]` on all types that occur more than once.

**Comment by XAMPPRocky** [comment]
> We take this issue to derive_more and ask to reintroduce this behaviour

Well I'm not the maintainer, but I think a reasonable proposal could be adding a container level parameter for the `from_derive` that provides this behaviour.

```rust
#[derive(From)]
#[from(ignore_conflicting_types)]
pub enum Foo {
    Foo(u32),
    Bar(u32),
}
```

> Add some extra logic in the autogenerator to emit #[from(ignore)] on all types that occur more than once.

I'd maybe go step further at that point and auto-generate the `From` impl in the crate and remove `derive_more` as a dependency entirely. 

Another option might be to move the `derive_more` crate into the `autogen` crate, and call the `derive_more::derive_from` at codegen time, so that the generated code only contains the `From` impls and doesn't require `derive_more` as a dependency.

**Comment by MarijnS95** [comment]
@XAMPPRocky I really like the idea of calling `derive_more::from_derive` at regen/autogen time to get rid of the "runtime" dependency completely. The signature takes and generates a `TokenStream` making it really easy to plug into the current solution. However, `derive_more` is a `proc-macro = true` crate, imposing all kinds of nasty restrictions on exports.

Working around that results in:
```
thread 'main' panicked at 'procedural macro API is used outside of a procedural macro', library/proc_macro/src/bridge/client.rs:331:17
```
:disappointed: 

Fixing the duplication in rspirv is a bit of a mess too as there's no comparison or hashing on `TokenStream`s. I can probably work the duplication check elsewhere in the code but stringifying is easiest: https://github.com/gfx-rs/rspirv/commit/c8f4b1e550b45b09a1f433d35b2611cff7aa1230

Note that I've only fixed `Operand` whose `::from` is actively used. We should probably apply the same treatment to `Decoration` if used externally.

I'm more inclined to fix this upstream, given that code for that was already available upstream at some point.
