### ISSUE TITLE
Name of the crate

### ISSUE THREAD

**Issue by neon64** [gfx-rs/rspirv#21]
First off, this isn't exactly an issue per se.

I was looking through my crates on `crates.io` and discovered I had a crate from 2 years ago named `spirv` - which I created just to support a hobby project before there were any other SPIR-V libraries in Rust. I haven't maintained it in ages and the code/features/testing/etc are quite obviously inferior to the fantastic work being done in this crate. So basically my question is, since I'm going to mark that as 'abandoned' and suggest that nobody should use it, would another crate (eg: this one) like to take that `spirv` name?

I realise this is perhaps a dumb question, since changing names on crates.io would force all the users of `rspirv` to change their code, however I guess I'm just letting you know in case somebody feels that `spirv` is a 'nicer' or more canonical name to use.

*Edit:* I guess I'm also looking for https://github.com/rust-lang/rust/issues/41616

**Comment by antiagainst** [comment]
Hi @neon64, much appreciated your generosity and kindness to transfer the `spirv` crate name! `spirv` sounds like a nicer name for the [header sub-crate](https://crates.io/crates/spirv_headers) in this repo. However, as you said, it is rather intrusive to change crate names under the current cargo/crate management settings. So I'm just not sure it worth the hassle.

**Comment by neon64** [comment]
Okay no worries.. Well maybe for now I'll just put a clear link to this project suggesting people go use it instead.

**Comment by antiagainst** [comment]
Thanks @neon64! :)

**Comment by antiagainst** [comment]
Hey @neon64, are you still willing to shift the ownership of the `spirv` crate to us now? Previously there isn't a need, but now it looks the need does arise: `spirv_headers` is using the SPIR-V version as the crate version; it has seen a few breakages thus far due to the differences from semver. It might be better to start with a clean slate to push to `spirv` crate where we can adopt semver from now on. WDYT?

**Comment by neon64** [comment]
@antiagainst I'd be fine to transfer ownership. Which username(s) should I invite?

**Comment by Jasper-Bekkers** [comment]
@Jasper-Bekkers, @kvark and @antiagainst at least I think :-)

**Comment by antiagainst** [comment]
Yes. Thanks @neon64!
