### ISSUE TITLE
Removal of `FromPrimitive` in enums broke instruction parsing in spirq

### ISSUE THREAD

**Issue by PENGUINLIONG** [gfx-rs/rspirv#250]
Hi, I wonder why FromPrimitive is removed in spirv 0.3? Spirq depends on such traits to parse instructions via generic calls and it has been a major blocking issue for me to upgrade.

**Comment by MarijnS95** [comment]
https://github.com/gfx-rs/rspirv/pull/219/files there should be a `pub fn from_u32()` alternative for you to use?

**Comment by PENGUINLIONG** [comment]
@MarijnS95 I found that though. But can we make a trait for it? Otherwise my whole parser infra just collapses..

**Comment by PENGUINLIONG** [comment]
Found a way to workaround it.
