### ISSUE TITLE
Improve codegen grammar typing

### ISSUE THREAD

**Issue by kvark** [gfx-rs/rspirv#45]
The biggest gain would be having strongly typed parsing results, e.g.
`if let Class::ModeSetting = inst.class  { ... }` instead of `if inst.class = "ModeSetting" { ... }`

We should evaluate the cost bringing the dependency, the amount of code removed from here, and the benefits.

**Comment by antiagainst** [comment]
I'm not sure which part you mean specifically?

**Comment by kvark** [comment]
Just realized it's already using serde-json. What confuses me is why `codegen::structs` module has all the things as `String`. Could stuff like `kind`, `quantifier`, and `class` be real enums instead of strings? That would improve codegen code quality a bit.
