### ISSUE TITLE
Port "mr" generators to tokens

### ISSUE THREAD

**Issue by kvark** [gfx-rs/rspirv#47]
The whole "codegen/mr.rs" is implemented to emit strings. This doesn't look nearly as tidy as `quote!`-based workflow of "codegen/sr.rs". We should make those consistent.

**Comment by antiagainst** [comment]
+1. I discovered `quote!` after done the MR generation. It's definitely much better than manipulating strings directly, but didn't get the chance to covert the existing implementation.
