### ISSUE TITLE
Licence headers out of date

### ISSUE THREAD

**Issue by AIOOB** [gfx-rs/rspirv#81]
All of the license headers state `Copyright 2016 Google Inc.`.
I feel like these should be being updated to the year they were last modified at the least. I'm also unsure as to what the licensing situation is with this project: references to Google are slowly disappearing; and it's licensed solely under Apache v2, whereas most of the rust ecosystem is dual-licensed under MIT/Apache v2 (I'm not actually sure if this can cause any issues, it might be worth looking into).
Changing the license is a real pain and a tricky business so it would make sense to get it right now before too many people touch the code.

**Comment by antiagainst** [comment]
I'm not a lawyer so I don't know all the nitty gritty on this; but I was told that the licence should be kept as-is when moving this project from google/ to gfx-rs/ and the code I wrote is copyrighted to Google. So I'd prefer to not open this can of worms. I think Apache v2 is permissive enough? Do you see any problem here?

For existing files, I think it makes sense to update the last updated time. And we can remove the headers for autogen'ed files.

**Comment by AIOOB** [comment]
I agree entirely I would prefer to change as little as possible.

The problem could be that downstream crates get forced to use Apache only as well, rather than the MIT/Apache mix that most will use. However, after reading both the licences I think it might be alright, although I'm not sure. We definitely can't put a NOTICE file in this repo because that puts conditions on all the downstream crates.

I think the license headers should be changed to `Copyright <year of creation> - <year last updated> the rspirv contributors`, although that year thing could be simplified. It's also debatable the headers even need to be there, but they aren't really causing a problem so they may as well stay.

**Comment by AIOOB** [comment]
After spending some time looking into this, I'm now happy that using Apache 2 won't cause any issues for downstream users.
The simplest and in my opinion cleanest solution to the headers getting out of date is to remove them entirely, the Apache licence does not require headers (see [here](http://www.apache.org/dev/apply-license.html#copy-per-file)) and it isn't even a file-level licence. The only reason the Apache project itself uses headers is so that someone looking at a source file in isolation immediately knows how it is licensed, to me this is a bit overkill.
This would reduce maintenance burden and would reduce the risk of having incorrect licensing.

**Comment by kvark** [comment]
@AIOOB I've been discussing this a while ago for gfx-rs repo and decided to remove all headers from the source files (for the same reason - it *appears* to not required, although the wording can be interpret differently). I would appreciate `rspirv` also not carrying around that useless stuff at the start of the files.

**Comment by antiagainst** [comment]
Thanks for taking the diligence to investigate this!
