### ISSUE TITLE
Optimize autogen build

### ISSUE THREAD

**Issue by kvark** [gfx-rs/rspirv#89]
On my machine, touching `autogen` module comes with a 35 second waiting penalty. It would be very useful for our productivity to make it faster.

**Comment by kvark** [comment]
First interesting discovery - my attempts to make SR autogen fast were not affecting the build times, because all SR takes less than 9 seconds of this time (20%). DR autogen is the rest.

Second discovery - all time is *actually* spent in `regex`. That seems promising to me.

**Comment by antiagainst** [comment]
Oh wow. `regex` is actually that bad? I didn't know about that. (Wasn't curious enough to do some profiling previously...)

**Comment by kvark** [comment]
Half of that slow was due to `Regex::new()` being called every time (instead of cached). Another half in the fact that `Regex::replace_all` was slow.
