### ISSUE TITLE
`Assemble::assemble(&self) -> Vec<u32>` always allocate heap memory

### ISSUE THREAD

**Issue by liigo** [gfx-rs/rspirv#96]

**Comment by Skepfyr** [comment]
Could you expand on this? I would have thought that assembly would almost always need to allocate somewhere, although I guess the return type could be made generic. What is the motivation here?

**Comment by kvark** [comment]
My reading is that we shouldn't take responsibility of allocation here. Instead, we should either accept an existing `&mut Vec<>` or return an iterator, allowing the users to allocate.

**Comment by paulkernfeld** [comment]
I see that there are a lot of uses of `Vec` throughout `rspirv` crate. So, even if `Assemble::assemble` didn't allocate, the crate would still need to make a lot of allocations internally. @liigo would this still be helpful to you?

**Comment by liigo** [comment]
yes, thank you.

**Comment by Jasper-Bekkers** [comment]
I think  #165 fixes this.
